import { Inter } from 'next/font/google';
import 'react-toastify/dist/ReactToastify.css';
import './globals.css';
import RoomsState from '@/context/rooms/RoomsState';
import UsersState from '@/context/users/UsersState';
import Toastbox from '@/components/ToastBox';

const inter = Inter({ subsets: ['latin'] });
export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<UsersState>
					<Toastbox />
					<RoomsState>{children}</RoomsState>
				</UsersState>
			</body>
		</html>
	);
}
